# Generated by Django 3.2.4 on 2021-07-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='food_category/image')),
                ('desc', models.TextField()),
                ('food_cost', models.DecimalField(decimal_places=4, max_digits=9)),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('murkup', models.FloatField()),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='food_category/image')),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'foods_categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
                ('client_location', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=255)),
                ('order_sum', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_count', models.IntegerField()),
                ('sum', models.DecimalField(decimal_places=4, max_digits=9)),
                ('food', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, to='appfood.food')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='appfood.order')),
            ],
            options={
                'db_table': 'orders_description',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='food_category_id',
            field=models.ForeignKey(db_column='food_category_id', on_delete=django.db.models.deletion.CASCADE, to='appfood.foodcategory'),
        ),
    ]
